"""
ScriptService handles creation and persistence of test scripts generated by the LLM.
"""
import os
from typing import Dict, Any, Tuple
from .storage_service import StorageService


class ScriptService:
    """Create and persist pytest+Playwright scripts for a test case."""

    def __init__(self, storage: StorageService | None = None) -> None:
        self.storage = storage or StorageService()

    # PUBLIC_INTERFACE
    def write_script_for_test_case(self, test_case_id: int, test_case: Dict[str, Any], script_content: str) -> Tuple[str, str]:
        """Write script file for a test case; returns (file_path, filename)."""
        dir_path = self.storage.script_dir_for_test_case(test_case_id)
        safe_name = test_case.get("name", f"tc_{test_case_id}").lower().replace(" ", "_").replace(":", "")
        filename = f"test_{safe_name}.py"
        file_path = os.path.join(dir_path, filename)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(script_content)
        return file_path, filename
